### ISSUE TITLE
Sommes suggestions

### ISSUE THREAD

**Issue by jeannen** [rplcnn/SuperGuilds#10]
Hey ! Here are my suggestions (I've posted them in the discussion, i put them here) :
- An achievement system (Like "Kill 10 players" , "Have 20 claimed land" etc...)
- Have daily mini-quests ("Kill 1 player from an ennemy guild", "Tame 5 pig" or others basic things like that that give some rewards)
- Add a "Guild banner" (Via command, like /guild setbanner), and the banner will be avaible to craft with a specific recipe for all players
- Add a guild bank, where guilds can store items and buy new chest (http://prntscr.com/78s8d9 : The enderchest is the chest where you are, the red wool are buyable chests)
- No /guilds give command, use a GUI instead
- Have a guild permission system with a GUI, and custom rank: http://prntscr.com/75fatp
  At the top this is the permission (Recruit new players, access to guild chest, etc...), at the left the Rank (The names can be customized by the guild's master) and at the center the perm (Allow/Deny) when the guild's master want to allow a perm' for a rank, he just have to click on the wool block !
- Guilds stats (Allways in a GUI) like this: http://prntscr.com/78s9um
- A guild golem that attack all players that are not in the guild (exept ally)
- A message when a player enter in a guild claim (A title message)
- A guild map (Where we can see all claimed lands)
- When we /guild create, it open a GUI (http://prntscr.com/78scp1)
  Ps: Sorry if my english is bad, i'm french

**Comment by Neotras** [comment]
I like it!! good

**Comment by rplcnn** [comment]
Wow thanks.

**Comment by rplcnn** [comment]
Update is coming soon.
![2015-05-28_22 58 25](https://cloud.githubusercontent.com/assets/11808988/7869917/5c3f81fe-058e-11e5-8e9e-fc5e69c182c7.png)
![2015-05-28_23 00 25](https://cloud.githubusercontent.com/assets/11808988/7869918/5c663290-058e-11e5-8703-40d6c22b422d.png)

**Comment by Neotras** [comment]
nice

**Comment by Neotras** [comment]
what is mit dynmap support

**Comment by rplcnn** [comment]
Working on "A message when a player enter in a guild claim (A title message)" feature. We add "ClaimTitleMessage" to config.yml

**Comment by jeannen** [comment]
Oh, and a "Can't claim WorldGuard region" option could be cool :)

**Comment by rplcnn** [comment]
Added spawn and guild regions protect.
Added PET SYSTEM :dancer:

**Comment by rplcnn** [comment]
Hey

**Comment by mistermantas** [comment]
Why did you re-open this issue?
