### ISSUE TITLE
Bugs and Suggestions - (Hurry Fix? :D)

### ISSUE THREAD

**Issue by Zhyther** [rplcnn/SuperGuilds#17]
Would it be possible to add "ClaimPVP: 'true'" to config file?
my players would love it

and when a player joins his/her guild this message only occurs - <none>

And for the buildings system to be either (Small) schematics or they make and pay for an upgrade to level 2

**Comment by rplcnn** [comment]
[ADDED] Would it be possible to add "ClaimPVP: 'true'" to config file?
my players would love it

[FİXED]  buildings system
