### ISSUE TITLE
Claims, Buildings, Land to claim and slots problems and a suggestion

### ISSUE THREAD

**Issue by Psycho611** [rplcnn/SuperGuilds#19]
if a stranger try to break from outside the land claimed the can do that but if they are inside the land claimed they cant. If u try to break something from inside the claimed land it says {GUILD}.

when i create a guild building it says <none> and the name of the building

why when i create a building i dont have more slots in the guild or more land to claim

Please add the user comman /g list to see all the guilds and an option to toggle the map on when u use /g map

**Comment by rplcnn** [comment]
Fixed thanks :)
