### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by SnowInori** [rplcnn/SuperGuilds#23]
When I put the plugin into the server it goes really slowly like it is about to die but the tps does not drop then when i take it out the server is fine and works really fast can you fix this?

**Comment by SnowInori** [comment]
23.07 13:38:11 [Server] ERROR 'player cannot build at the player's location' is not a boolean (yes/no) (SuperGuilds.sk, line 1094: if player cannot build at the player's location:')
23.07 13:38:10 [Server] ERROR 'player cannot build at the loop-block' is not a boolean (yes/no) (SuperGuilds.sk, line 866: if player cannot build at the loop-block:')

**Comment by SnowInori** [comment]
these are errors I am getting

**Comment by rplcnn** [comment]
Install WorldGuard (or a grief protection plugin)

**Comment by rplcnn** [comment]
I looking for your lag problem.

**Comment by rplcnn** [comment]
Can you use http://timings.aikar.co/
? And send resoults to me

**Comment by SnowInori** [comment]
http://timings.aikar.co/?url=11926820

**Comment by SnowInori** [comment]
I installed world guard and it is not working still its does not seem like lag per say it seems like the server is taking a while to get through stuff only when this plugin is installed

**Comment by rplcnn** [comment]
Can you give scripts folder ss? I want show your skripts :) (I using SuperWalls and SuperGuilds and my  server is lagless tps= 19.87

**Comment by SnowInori** [comment]
do you have skype so we can talk this out?

**Comment by SnowInori** [comment]
http://prntscr.com/7w7qwd
http://prntscr.com/7w7rb4

**Comment by SnowInori** [comment]
thats what I have in my scripts folder

**Comment by SnowInori** [comment]
my host is also mspro hosting

**Comment by rplcnn** [comment]
delete all scripts and install only superguilds

**Comment by SnowInori** [comment]
still did not fix the problem

**Comment by rplcnn** [comment]
okay disable scoreboard

**Comment by SnowInori** [comment]
even when I turn the scoreboard off it continues to turn itself back on is there anyway I can just have you come on the server and see what the problem is?

**Comment by rplcnn** [comment]
Sure, add my skype: scheer_13

**Comment by mboisvertdupras** [comment]
I have this problem too. I added you on skype.

**Comment by rplcnn** [comment]
Okay, Can you send timings?
