### ISSUE TITLE
Claim time feature not working and suggestion for claims and others

### ISSUE THREAD

**Issue by Psycho611** [rplcnn/SuperGuilds#25]
This is the suggestion, you could add a vault feature so every player need money to buy each claim, like this 1 claim = 10 coins but the next claim will cost 20 coins and more and more, so the cost of the claim will be increased each time they made a claim. The initial cost of the claim will be configurable in the main config file the "config.yml".
Could you add the posibility of execute commands when you win a war? to reward the winners with commands of other plugins like ranks, tokens etc.

**Comment by rplcnn** [comment]
ADDED WIN COMMAND
