### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by rplcnn** [rplcnn/SuperGuilds#3]
- An achievement system (Like "Kill 10 players" , "Have 20 claimed land" etc...)
- Have daily mini-quests ("Kill 1 player from an ennemy guild", "Tame 5 pig" or others basic things like that that give some rewards).
- Add a "Guild banner" (Via command, like /guild setbanner), and the banner will be avaible to craft with a specific recipe for all players
  Have a guild permission system with a GUI, and custom rank: http://prntscr.com/75fatp

**Comment by Neotras** [comment]
please support Beton quests

**Comment by rplcnn** [comment]
Beton quests?
