### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by controlorCZ** [rplcnn/SuperGuilds#35]
> [13:02:15 WARN]: [Skript] Possible name conflict of variables {sg::war::teleport::guild1} and {sg::war::teleport::%arg 3%} (there might be more conflicts). (SG-Wars.sk, line 161: teleport {_player} to {sg::war::teleport::guild1}')
> [13:02:15 WARN]: [Skript] Possible name conflict of variables {sg::war::teleport::guild2} and {sg::war::teleport::%arg 3%} (there might be more conflicts). (SG-Wars.sk, line 206: teleport {_player} to {sg::war::teleport::guild2}')
> [13:02:15 WARN]: [Skript] Possible name conflict of variables {sg::LoncaTipi::guild1} and {sg::LoncaTipi::%{_g1}%} (there might be more conflicts). (SG-Wars.sk, line 212: set {sg::LoncaTipi::guild1} to "%{_g1}%"')
> [13:02:15 WARN]: [Skript] Possible name conflict of variables {sg::LoncaTipi::guild2} and {sg::LoncaTipi::%{_g1}%} (there might be more conflicts). (SG-Wars.sk, line 213: set {sg::LoncaTipi::guild2} to "%{_g2}%"')
> [13:02:15 WARN]: [Skript] Possible name conflict of variables {sg::warOyuncular::%{sg::warOyuncu::takim::%uuid of victim%}%::_} and {sg::warOyuncular::guild1::_} (there might be more conflicts). (SG-Wars.sk, line 247: if size of {sg::warOyuncular::%{sg::warOyuncu::takim::%uuid of victim%}%::*} is less or equal to 1:') 
> When i write command /sg -> NONE NONE NONE NONE on all lines

**Comment by rplcnn** [comment]
Thanks for report, for conflict warnings: https://www.spigotmc.org/wiki/superguilds-faq/?noRedirect=1

For NONE; install SG-Files.sk and use /sk reload SG-Files command.
