### ISSUE TITLE
Chat Prefix Issue

### ISSUE THREAD

**Issue by Htgan** [rplcnn/SuperGuilds#37]
Player without a guild who joins the server will have this :
<none>
as their prefix, for example my username is Htgan and on first join my chat will looks like:
<none>Htgan asdf
Once I create a guild (named Zombagz), my chat will look like this:
- [Zombagz] <none>Htgan asdf
  and once I disband and then re-create a guild (named ZZZZ), my chat will look like this:
- [ZZZZ] \* [Zombagz] <none>Htgan asdf

Relogging does not solve this issue.

**Comment by rplcnn** [comment]
New version?, oh no I have to fix again, Thanks :+1:
