### ISSUE TITLE
Creating and Deleting Guild

### ISSUE THREAD

**Issue by Htgan** [rplcnn/SuperGuilds#38]
Both Creating and Deleting a guild causes massive hang of the entire server.
Every time you create or delete a guild, the entire server is paused for about 5 seconds.
Chats/commands will not go through. Server will not even respond to ping and accept player joins. Tested on local server so there is no internet delay.

Also, deleting the guild is so easy to do by accident, as there is no confirmation for deleting a guild. You can work hard for weeks on a guild and  accidentally click the bucket and poof your guild is gone. MOVE THE DELETE GUILD ICON to somewhere you can't click by accident and ADD CONFIRMATION for deleting guild.

**Comment by rplcnn** [comment]
XD I will do this. (like /g debug command)
