### ISSUE TITLE
Perms bug still not fixed.

### ISSUE THREAD

**Issue by Duqino** [rplcnn/SuperGuilds#4]
Hey,

I just found out that the perms bug is still not fixed in the 0.4.4 version
I placed the guilds.player and the guilds.admin perms where they need to be, but i cant even leave my test guild.

http://gyazo.com/d910cf4f6664b78061d907e29742634b

King regards,

Duqino.

**Comment by rplcnn** [comment]
Thanks for bug. Fixed!
https://github.com/rplcnn/SuperGuilds/blob/master/PermissionRework
