### ISSUE TITLE
Guilds interfering with prefixes

### ISSUE THREAD

**Issue by Kaasblokje150** [rplcnn/SuperGuilds#43]
Hello,
I have a problem with the guild plugin. For some reason the plugin gives people a prefix in a world instead of using the prefix that is included with the rank so if someone changes to a different group with a other prefix the prefix ingame will still stay the same.

Here is a example:

  aab5d4e9-fc6e-315b-a3a1-1c8aadb2e6fe:
    group:
    - Owner
    options:
      name: kaasblokje150
    worlds:
      world:
        options:
          prefix: '&8[&6Owner&8]&6 '

**Comment by rplcnn** [comment]
Hmm, i wil fix
