### ISSUE TITLE
Erro with Skript

### ISSUE THREAD

**Issue by dgateles** [rplcnn/SuperGuilds#46]
Super Guilds get erro with skript:
http://prntscr.com/ad6dj2

**Comment by rplcnn** [comment]
Spigot version?

**Comment by dgateles** [comment]
1.8.8

2016-03-12 18:17 GMT-03:00 Doğukan notifications@github.com:

**Comment by rplcnn** [comment]
Use that file: http://pictures.superguilds.tk/uploads/2016/03/SG-Files.sk

(File will be removed in 24 hours.)
