### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by dj2553** [rplcnn/SuperGuilds#52]
Hello
I am having problems getting your Skript to work. First I have all dependency's that were listed in the Read me File with the zip I have installed/uploaded all the required Files Into the Skript folder and restarted my server. At First it looked like it was working all commands were running and I could use the Admin commands But after I Created my first Guild I started to get errors such as when I started to use the guild commands such as /g sethome, /g home, /g claim, /g pet, /g chest and many more commands it told me it was disabled. After seeing this I went to the Config of the plugin/ Skript to see if I needed to enable it in the world but the Config files was empty and I tried deleting the plugin files and restarting my server and this still did not fix the plugin. Last problem I am having is that the Buildings are NOT working. When ever I try to make a Town hall it never works (In my building folder the .YML file in there is Empty as well), it pops up with the build time but never builds anything I don't know if I need to upload my Own files for this but as of now the including one is not working. Over all the Look and Feel of the Plugin is Great I would love to use it on my server if you could help me fix these issues my server is running minecraft 1.8.8 and has the Following plugin World Edit, Multiverse-core, VoxelSniper, Skript, WildSkript, SkQuery and all the Skript plugins are at a 1.8 up version that's compatible with 1.8.8

**Comment by rplcnn** [comment]
Thanks. We'll publish hotfix version in today.
