### ISSUE TITLE
Builds Still Dont Work

### ISSUE THREAD

**Issue by dj2553** [rplcnn/SuperGuilds#53]
Hello
you have just posted a Hot Fix for the Plugin and this has fixed all my other problems but the Builds Still are not working. When I create a Guild it tells me to stand on the Glowstone with a gold area around it and it says you must stand in the Chunk, so I did and Ran the Command again and it did not make a Home/Base it just made a Hole in the ground. Also Non of the other Builds are working as well, such as the Town Hall, Store, Alchemist, and Sawmill they have a Timer with a Boss-bar but nothing happens or is Built.

**Comment by rplcnn** [comment]
I see. I will fix that. Thanks

**Comment by DDematto** [comment]
Please Also Notify me when this is fixed :) Thanks :+1:

**Comment by rplcnn** [comment]
Fixed :+1:
