### ISSUE TITLE
URGENT! Schematics Overide WorldGuard Regions

### ISSUE THREAD

**Issue by DDematto** [rplcnn/SuperGuilds#57]
Latest Update Schematics Now Work! But Now there are a Bunch of Houses In My Spawn! For Some Reason. Something broke That they no longer follow Any WorldGuard Flags, (Yes it is Set To True In Config)

Plz Fix!

**Comment by rplcnn** [comment]
Send me console logs please. ( players cannot create guilds in wg regions?)

**Comment by DDematto** [comment]
Players Can Create Guilds In Wg Regions

This is all its giving me 

http://pastie.org/10891722

It Does prevent it in the region at some points but if i jump and do the command or something like this it breaks

**Comment by DDematto** [comment]
Also A Quick Question Is there Schematics to load in for the shops or markets and all that instead of the home because im trying to figure out the upgrade buildings system and when i try to upgrade town hall nothing changes around me, same with the other upgrades

**Comment by rplcnn** [comment]
we working on it.

**Comment by DDematto** [comment]
Any Fixes to it?

**Comment by rplcnn** [comment]
Change your skript plugin.
