### ISSUE TITLE
doing /superguild not working

### ISSUE THREAD

**Issue by matthewtrains** [rplcnn/SuperGuilds#58]
Hi I'm running a 1.9 server and I did /superguild help and it come out saying none what do I do to fix this
![2016-07-15_07 30 03](https://cloud.githubusercontent.com/assets/20475752/16872918/01516936-4a5e-11e6-9164-d569479a5798.png)

**Comment by matthewtrains** [comment]
this is from the consol 15.07 07:37:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
15.07 07:37:49 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
15.07 07:37:49 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
15.07 07:37:49 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
15.07 07:37:49 [Server] INFO at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.command.Commands.handleCommand(Commands.java:260) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.util.Task.callSync(Task.java:139) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:50) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at ch.njol.skript.Skript.dispatchCommand(Skript.java:935) [Skript.jar:?]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-a1b8bf3-f01861f]
15.07 07:37:49 [Server] INFO org.bukkit.event.EventException
15.07 07:37:49 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to Commandspy v3.1.2
15.07 07:37:49 [Server] INFO Matthewtrains: /sg help 1
15.07 07:37:49 [Server] INFO Matthewtrains: /g help
15.07 07:37:49 [Server] INFO Matthewtrains: /superguilds
15.07 07:37:49 [Server] INFO Matthewtrains issued server command: /superguilds

**Comment by matthewtrains** [comment]
Nvm just got updated verson from the update list in the plugin from republicansensei.com

**Comment by matthewtrains** [comment]
Now its not building stuff let me restart to see if it fixes it

**Comment by matthewtrains** [comment]
worked now :)

**Comment by matthewtrains** [comment]
I need all the building scematics for the plugin it wont build some stuff

**Comment by rplcnn** [comment]
The plugin builds only Guild Home. :+1:

**Comment by matthewtrains** [comment]
then how do I get the outher ones

**Comment by rplcnn** [comment]
no way for now.
