### ISSUE TITLE
Guilds <None> tag and spam help.

### ISSUE THREAD

**Issue by BiGUNMAN** [rplcnn/SuperGuilds#6]
When typing /g or /guilds for the list of commands. Please make it divided into pages. The <none> tag in some areas is also odd.

Gif of the length, and the <none>.
http://gyazo.com/0809d0e9743eacc28b7d6509a0609093

**Comment by rplcnn** [comment]
Delete messages.yml and try again.

**Comment by Neotras** [comment]
i have the plugin new install
