### ISSUE TITLE
Hi I got this error:

### ISSUE THREAD

**Issue by HazeGaming** [rplcnn/SuperGuilds#60]
http://hastebin.com/uqupilosut.avrasm (I use republicasensei.com .jar)

**Comment by rplcnn** [comment]
Did you try other SkQuery?

**Comment by HazeGaming** [comment]
I've tried using last 1.8 SkQuery relase

**Comment by rplcnn** [comment]
Try other.

**Comment by HazeGaming** [comment]
Fixed!

**Comment by HazeGaming** [comment]
Found new issue: when I do /f chat i can't write in chat, when I disable faction chat i can
