### ISSUE TITLE
Chat Prefix witch essentialschat 

### ISSUE THREAD

**Issue by SerCat1** [rplcnn/SuperGuilds#67]
Hello, can you tell me how to put the name of the guild in the chat with essentialschat ?
thank you very much.
Ps : Sorry for my bad english.

**Comment by rplcnn** [comment]
Put {GUILDNAME} to essentials config.yml

**Comment by SerCat1** [comment]
It does not work :-(
Get screenshot here : http://prntscr.com/ebk4sd
