### ISSUE TITLE
Bug with Essentialschat

### ISSUE THREAD

**Issue by SerCat1** [rplcnn/SuperGuilds#68]
I put {GUILDNAME} in config.yml, but he does not work :-( 
Get screenshot here : http://prntscr.com/ebk4sd
sorry for my bad english.

**Comment by rplcnn** [comment]
Did you install superguilds_groupmanager?

**Comment by SerCat1** [comment]
Yes, it is indeed already installed
http://prntscr.com/ebp98e

**Comment by rplcnn** [comment]
Skype: republicandogukan
