### ISSUE TITLE
Can break blocks in Townhall zone

### ISSUE THREAD

**Issue by airoons** [rplcnn/SuperGuilds#69]
Hello!

There is a bug with your faction Townhall zone - if you are in it, you can't break blocks, but if you are outside of it, you can. Please fix!

Edit: With "you can break blocks" I meant you can be outside Townhall zone and break blocks in Townhall zone...

**Comment by rplcnn** [comment]
Okay, thanks.

**Comment by rplcnn** [comment]
(Fixed in my version, I will publish in few days)
