### ISSUE TITLE
Command Usage

### ISSUE THREAD

**Issue by BiGUNMAN** [rplcnn/SuperGuilds#7]
When typing /g create [name] it tells you to "Please enter guild tag." by default, instead of saying: "Please enter guild tag: /g create [name] [tag]"

Additionally: 
http://gyazo.com/6aad2299dc81e65cc5740d0b074ada9c

When I finally correctly entered the Syntax it tells me "You arent leader of guild." and the lines after that also.

Pretty broken atm...

**Comment by BiGUNMAN** [comment]
Also, /g kick doesn't work.

**Comment by Neotras** [comment]
/g info doesnt work "you have not permission"

**Comment by rplcnn** [comment]
We working on permission and command.

**Comment by Neotras** [comment]
tanks
