### ISSUE TITLE
Doesn't work on 1.11

### ISSUE THREAD

**Issue by BlueYoshi68** [rplcnn/SuperGuilds#71]
first off, this: http://pastebin.com/CHwQ341E

2ndly, the  link  for SkQury and WildSkript dont work...

(these 2:
	-> SkQuery: http://republicansensei.com/SkQuery%201.7-1.8-1.9.jar
	
	
	-> WildSkript 1.7-1.8: http://republicansensei.com/WildSkript%201.7-1.8.jar
	or
    -> WildSkript 1.9-1.10: http://republicansensei.com/WildSkript%201.9-1.10.jar)

**Comment by rplcnn** [comment]
These are working in my test server (version 1.11)

**Comment by BlueYoshi68** [comment]
cause the link you give people in the text document is a private link. the author already gave me a working one
