### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by airoons** [rplcnn/SuperGuilds#74]
Those pull requests doesn't work for me, so I'll write my suggestions here:

**1. Guild chat**
I suppose this feature is not completed now, so I would like to see it... Just a simple toggle-able chat (/g chat), because it might be frustrating to type "/g chat [message]" every time you want to use guilds chat.

**2. Allies**
A simple feature so you could add a ally guilds (/g ally [guilds name]), in my opinion the best purpose for this would be for Guild chat (Ally chat) - you could switch by executing "/g chat" multiple times to use Ally chat or command "/g chat ally". In such Ally chat your messages will be visible only to your faction and all allies to your faction.

**3. Guilds map**
As seen on Faction plugins, I would like to see a simple Map feature. The best way would be to show map in chat, as reference you can research Factions plugin map (http://prntscr.com/elgpbm). So if you would type "/g map" in chat you would see chunks around you and guilds in them. If it is possible, it would be awesome if there would be also a "/g map on" and "/g map off" command so you could toggle map's auto-updating (if you move for few chunks, the map sends again to your chat, so you don't need to spam /g map command).

**4. Online players in guild**
Add a functionality for online players in guild, so there would be a variable for COUNT of online players in guild, also if you use "/g info" command to check a faction, you could see in there which players are online in guild.

**5. All guilds list**
Many of these suggestions is from factions plugins, so this is one of them too - add a simple command "/g list" (so change current "/g list" command to "/g members", which makes more sense), which will show all guilds in chat, for example (divided by pages, for example, 10 guilds per page, you could click on chat arrow to go to next page or use command "/g list [page]" to see other pages). They could be sorted by many options, like member count, claimed chunks count etc.

For now this will be it, I'll probably create a separete "suggestion" after some time, I wish you will add these suggestions!

**Comment by rplcnn** [comment]
1- Done. (That will come in today's update.)
2- That will come in next update.
3- That won't come. 
4- Done. (That will come in today's update.)
5- That will come in next update.
