### ISSUE TITLE
Bugs #1

### ISSUE THREAD

**Issue by Neotras** [rplcnn/SuperGuilds#8]
1. land claim dosn't work he say "you dont have a guild"  But I have a guilde
2. Guild home is not working . I will not be teleported to the home.
3. I get in the chat no tag before the name
4. I can donate no wood
5. You will see two times / Guilds description
6. you will see tow times /guilds buildings
7. i can't not wirte in the guilds chat

**Comment by rplcnn** [comment]
TR Translate:
1. Alan claimi çalışmıyor. Loncam olsa bile "Loncan yok" diye hata veriyor.
2. Lonca evleri çalışmıyor. Eve ışınlanmıyorum.
3. Chatta tag yok.
4. Tahta bağışlamıyorum.
5. Lonca açıklaması 2 defa gösteriliyormuş.
6.  /guilds buildings komutu 2 defa gösteriliyormuş.
7. Lonca sohbeti çalışmıyormuş.

Thanks for bugs. We will fix.

**Comment by Neotras** [comment]
the next update come???

**Comment by rplcnn** [comment]
Today.

**Comment by Neotras** [comment]
yes i love that

**Comment by rplcnn** [comment]
FIXED AND UPDATED!
