### ISSUE TITLE
Cannot disable buildings?

### ISSUE THREAD

**Issue by ArgonGaming** [rplcnn/SuperGuilds#82]
Is there a way to just leave the plugin as a normal factions server in the config with claims and all, and not have the townhall or any of the buildings system in place?

**Comment by rplcnn** [comment]
Sorry, i will do new premium resource for this.

**Comment by ArgonGaming** [comment]
Thank you so much for replying and considering the idea of it in general! I will pay it for sure once its out ;D Maybe send me a link once it is

**Comment by rplcnn** [comment]
<3 Thanks

**Comment by ArgonGaming** [comment]
How long would it take for u to do something like that? Estimated

**Comment by rplcnn** [comment]
Next Week I can start to code

**Comment by ArgonGaming** [comment]
Oh yeah, and will this post close once its finished?

**Comment by rplcnn** [comment]
Yeah

**Comment by ArgonGaming** [comment]
Its finished then?
