### ISSUE TITLE
General errors 

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [rplcnn/SuperGuilds#86]
Just to inform u that superguild still doesn't work.

I take it from a while and I never used it.

when u will fix my issues?

https://pastebin.com/wVAZsshq

With your latest update: 4.9.4
inventory click doesn't work... 
when I click on an object, it remains in my hand

and some items in menu are not showed

**Comment by rplcnn** [comment]
Console log?

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I already sent u all what I have

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I already told u, come to my server to see yourself

mc.herosfaith.eu

let me know when u come, becouse server is closed

**Comment by rplcnn** [comment]
I fixed.
