### ISSUE TITLE
Bugs 0.4.6

### ISSUE THREAD

**Issue by Neotras** [rplcnn/SuperGuilds#9]
1.Name tag is not properly agezeigt there is only <none> appears
2./ guilds description we still appears twice
3.In Guild Nexus is a & sign in front . ( I think that there does not have to go )
4.you do not click on the dragon egg that does not open the inventory .
5.in / sg buildngs will sign before a sawmill " & " appears
6.The alchemy menu does not open
7.if you " / guilds help" fehen typing at the commandos , the " s " in the " guilds "
8.the <none> will delete the tag from permissioneX
    befor [ Admin ] Neotras
     than < None > Neotras
     Best- > BZP [ CPW ] [ Admin ] Neotras
->there 's more to come

**Comment by rplcnn** [comment]
TR Translate>
1. İsim etiketi düzgün görülmüyor.
2. /g description 2 defa görülüyor.
3. Lonca merkezi yazısı bozuk. (Lonca bilgileri kısmında)
4. Ejder yumurtasına tıklanmıyor.
5. /sg buildings te değirmen (sawmillin) "&" hatası var.
6. Büyü (alchemy) menüsü çalışmıyor.
7. /guilds help komutunda yazım yanlışı yada hata var.
8. PermissionEx deki tagları siliyormuş
Önceden [Admin] xxx ken şuan <none> xxx oluyormuş.
Thanks for bugs.
